# Generated by Django 2.2.11 on 2020-04-17 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedStockAnalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(default='0', on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
