# Generated by Django 2.2.11 on 2020-03-09 14:30

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedStockAnalist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', jsonfield.fields.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedStockAnalist.Analysis')),
            ],
        ),
    ]
