# Generated by Django 2.2.11 on 2020-03-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedStockAnalist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='report',
            new_name='synthesis',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='created_by',
        ),
    ]
