# Generated by Django 2.2.11 on 2020-04-17 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedStockAnalist', '0002_analysis_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
