# Generated by Django 2.2.11 on 2020-04-20 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedStockAnalist', '0005_auto_20200420_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
