# Generated by Django 2.2.11 on 2020-03-16 19:56

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('synthesis', djongo.models.fields.DictField()),
            ],
        ),
        migrations.CreateModel(
            name='MissingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', djongo.models.fields.DictField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedStockAnalist.Analysis')),
            ],
        ),
    ]
